stages:
  - build
  - test
  - deploy
  
build:
  stage: build
  script:
    - docker build -t -api-java .
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker tag api-java $DOCKER_USERNAME/api-java:latest
  
  only:
    - main
test:
  stage: test
  script:
    - docker pull $DOCKER_USERNAME/api-java:latest
     - docker run $DOCKER_USERNAME/api-java:latest java -cp /app /greeting-api/src/test/java/cl/ionix/test/greetingapi/GreetingApiApplicationTests.java

deploy:
  stage: deploy
  script:
    - kubectl apply -f deployment.yaml
    - kubectl apply -f service.yaml